### ISSUE TITLE
build_num.exe requires to install Visual Studio 2010 C++

### ISSUE THREAD

**Issue by ujeenator** [shtras/BlindAM#1]
build_num.exe requires MSVCP100D.dll which is part of C++ 2010 redistributable package for debug and it contributed only as a part of Visual Studio 2010 C++

It is very confusing, because project sources need to be compiled for C++ 2012 redistributable package, which contributed as part of Visual Studio 2012

So I need to install both IDE to compile sources :(

DUH!

**Comment by shtras** [comment]
As a temporary solution I've added both msvcp100d.dll and msvcr100d.dll, required by build_num.exe. Alternatively you can remove it from the "Build Events->Pre-Build Event->Command Line" setting in the solution. The only thing it does is increasing the build number.
Later on I'll recompile it using 110-th toolset.
