### ISSUE TITLE
The BlindAM cann't be compiled under 32-bit linux.

### ISSUE THREAD

**Issue by o01eg** [shtras/BlindAM#3]
Rev: 29e906fd0b02c306d4509495d05a6f3d1faf24cf

```
BoxCar.cpp:156:12: error: ‘sleep’ was not declared in this scope
```

It fixed by adding '#include <unistd.h>'

```
/usr/bin/ld: skipping incompatible ./libengine.so when searching for -lengine
/usr/bin/ld: cannot find -lengine
collect2: error: ld returned 1 exit status
```

**Comment by shtras** [comment]
That's correct, the library is 64 bit.
I've added 32-bit version. Use make all ARCH=32

**Comment by o01eg** [comment]
First error still exists:

```
BoxCar.cpp:156:12: error: ‘sleep’ was not declared in this scope
```

It can be fixed by adding '#include &lt;unistd.h&gt;'

**Comment by shtras** [comment]
I'm not getting this error at my end, so can't reproduce and verify.
