### ISSUE TITLE
Cannot run BlindAM

### ISSUE THREAD

**Issue by dmytrokyrychuk** [shtras/BlindAM#4]
I am getting this error when I am trying to run this program. 

```
orgkhnargh@laptop:~/code/BlindAM$ ./BlindAM
./BlindAM: error while loading shared libraries: libengine.so: cannot open shared object file: No such file or directory
```

libengine.so library exists and lies in BlindAM's directory.
Compilation seems to be ok, I deleted SDL folder before compilation. Did anybody experienced such error?

**Comment by shtras** [comment]
Hi
Have you tried
export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
?

**Comment by dmytrokyrychuk** [comment]
It helped. Thank you. Everything seems fine now.
