### ISSUE TITLE
Closing after working fine for a pretty long time.

### ISSUE THREAD

**Issue by Xazzzi** [shtras/BlindAM#5]
Getting this in terminal:
BlindAM: World.cpp:173: void World::step(): Assertion `car->numWheels() < settings_->getNumWheelGenes()' failed.

**Comment by shtras** [comment]
Did you use the default parameters in the main menu? If not, could you please specify your setup?
For how long did you run the simulation?
This is indeed interesting bug to reproduce.

**Comment by Xazzzi** [comment]
As far as i remember, i used smaller population setting, around 50-100, and higer mutation rate (15). For everything else default value was left. Also, when i set max_wheels setting equal to max vertices number, i didn't get a crash, waited about 1 hour and that worked perfectly well.
I believe this happens when after mutation new car has more wheels then allowed in setting, but instead of discarding that one car BlindAM just halts.

Кстати, вы вроде как на русском говорите?

**Comment by shtras** [comment]
Found a bug and (hopefully) fixed it. Thanks for the feedback.

Да, говорю :)
